general:

  # Maximum packet index in bytes
  # If you have any issues with this, please set this to a higher value. (2048, 4096, ...)
  maximum-packet-index: 1024

  # Maximum packet size in bytes
  # If you have any issues with this, please set this to a higher value. (2048, 4096, ...)
  maximum-packet-bytes: 2048

  # Maximum packet capacity in bytes
  # If you have any issues with this, please set this to a higher value. (2048, 4096, ...)
  maximum-packet-capacity: 4096

  # Minimum online keep alive tick to automatically whitelist online players
  minimum-tick-to-auto-whitelist: 3

  # Enable this if you are using the motd of a spigot instance (forced host)
  allow-forced-host-ping: false

  # The ClientConnectEvent is thrown whenever someone connects to your server
  # This could be used by some plugins, so please enable it if it causes issues
  use-client-connect-event: false

  # The proxy protocol is used by reverse proxies
  # Enable this if you want to use a reverse proxy with Sonar
  # You need to enable proxy protocol in the BungeeCord configuration too
  use-proxy-protocol: false

  # Disable this if you don't want players/bots that are in the verification cache
  # to be cleared automatically when there are too many connections at the same time
  automatically-remove-bots-from-verifying: true

  # Enable this if you want to see all incoming connections in the console
  # It's highly recommended leaving this disabled because it will flood your console
  # during a bot attack
  log-connections: false

  # Number of minimum joins per second before toggling anti bot mode
  # You can change this number depending on your Minecraft servers' popularity
  minimum-joins-per-second: 6

  # Number of maximum online accounts per ip address
  maximum-online-per-ip: 2

  # Refresh delay of the action bar counter (in milliseconds)
  action-bar-counter-delay: 80

  # Number of accounts being removed from the queue
  queue-poll-rate: 2000

  # Some custom 1.19.1/1.19.2 client or mod packs do not send a valid player public key
  # Disable this if you have experience any issues
  force-valid-public-key: true

  # Number of maximum accounts being removed from the queue
  maximum-queue-poll-rate: 2000

  # Number of maximum joins per ip per 0.5 seconds (500ms) to kick the player
  maximum-joins-per-ip: 3

  # Number of maximum joins per ip per 0.5 seconds (500ms) to temporarily blacklisting the ip
  maximum-joins-per-ip-blacklist: 9

  # Disable this if you don't want Sonar to cache all server list pings
  # This is really powerful against motd/ping spamming attacks
  cache-incoming-motd-requests: true

  # Enable this if you still want Sonar to call the ProxyPingEvent during an attack
  # It is recommended to leave this 'true' but you can disable this if you have
  # plugins that rely on the ProxyPingEvent even during attacks
  # It is also recommended to use the built-in BungeeCord motd system
  no-ping-event-during-attack: true

  # Number of maximum status requests (pings) before Sonar should not call the ProxyPingEvent anymore
  maximum-status-requests-for-attack: 256

  # Server brand/version that is going to be displayed in the server list
  fake-server-brand: 'Sonar'

  # Server brand that is going to be displayed in the F3 menu
  # You can use the following variables:
  #   %proxy% - Brand/version of the proxy server
  #   %backend% - Brand/version of the backend server brand
  fake-server-client-brand: '(Sonar) %proxy% <- %backend%'

anti-proxy:

  enabled: true

  # Timeout for the anti-proxy web api (blackbox)
  # You can add custom anti-proxy apis by using the Sonar API
  timeout: 4000

checks:
  reconnect:

    enabled: true

    # The first-join check is really powerful and probably defeats most bot attacks
    # If you don't like it you can disable it, but it's not recommended to do that
    first-join: true

    # Delay in milliseconds a player need to wait before being able to successfully
    # rejoin the server (Recommended values: 500 - 5000)
    rejoin-delay: 2000

    # Enable this if you want to eliminate most Minecraft bot services
    # Players will need to ping the server in their server list before they are
    # able to join
    ping-before-join: false

  invalid-name:

    enabled: true

    # Maximum length of a name
    max-length: 16

    # This is the regex for invalid names
    # Names with special characters are automatically detected by this regex
    # If you want to add more, custom regexes, you can do that below this option
    regex: '^[a-zA-Z0-9_.]*$'

    # Blacklist mode for custom regexes
    # Options: ALWAYS, NEVER, DURING_ATTACK
    blacklist-custom-regexes: 'DURING_ATTACK'

    # Check mode for custom regexes
    # Options: ALWAYS, NEVER, DURING_ATTACK
    check-custom-regexes: 'DURING_ATTACK'

    # You can provide your custom name regex here
    # Only edit this if you know what you're doing
    custom-regexes:
      - 'MCSTORM_IO_+.{1,7}'           # This blocks all McStorm names
      - '.{1,5}StormStresser.{1,5}'    # This blocks all Storm stresser names
      - 'SNBKBOOT_+.{1,7}'             # This blocks all SNBKBoot names
      - 'XDDD_OK_+.{1,8}'              # This blocks some other weird names
      - '^[0-9]*$'                     # This blocks all names which are only numbers (only use this during attacks!)
      # Feel free to add more regexes or submit one as a GitHub feature request

notifications:
  webhook:

    # Enable this if you want to use Discord Webhook notifications
    enabled: false

    # The url of the Discord Webhook
    url: ''

    # The delay between each Webhook alert in milliseconds
    delay: 240000

    # The title of the Discord Webhook alert
    title: 'Sonar Antibot notification'

    # You can use the normal Discord formatting here
    format:
      - '> :warning: **Sonar has detected an incoming attack on your Minecraft server** :warning:'
      - '> '
      - '> Connections per second during the attack: **%cps%**'
      - '> Ip addresses per second during the attack: **%ips%**'
      - '> Global CPU load (average/total): **%cpu-avg%%** / **%cpu%%**'
      - '> Online players (right now): **%online%**'

    # Color of the Webhook Embed Object (left sidebar)
    # You can use https://rgbacolorpicker.com/ for some ideas
    color:
      r: 255
      g: 255
      b: 255
