name: Feature request
description: Suggest a feature to improve the plugin
title: "Request"
labels: ["enhancement"]

assignees:
  - jonesdevelopment

body:
  - type: textarea
    id: general
    attributes:
      label: "General information"
      description: |
        Please provide some information about the feature you would like to have implemented in Sonar Anti Bot. Is it related to a problem?
        Are there any screenshots or video showing the feature to better understand your request?
      placeholder: |
        Screenshots:
        - ...
        - ...
    validations:
      required: true

  - type: textarea
    id: reason
    attributes:
      label: "Reason"
      description: |
        Could you explain why you want this feature implemented in Sonar Anti Bot? Is there a specific reason?
      placeholder: |
        ...
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: "Additional information"
      description: |
        Is there any additional information you want to provide?
      placeholder: |
        - ...
    validations:
      required: false

  - type: dropdown
    id: can_be_found
    attributes:
      label: "Can this feature be found in other existing plugins?"
      multiple: false
      options:
        - "Yes"
        - "No"
        - Unsure
    validations:
      required: true
